-- 코드를 입력하세요
SELECT b.AUTHOR_ID AS AUTHOR_ID, a.AUTHOR_NAME AS AUTHOR_NAME, b.CATEGORY AS CATEGORY,
    SUM(bs.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK b, AUTHOR a, BOOK_SALES bs
WHERE b.BOOK_ID = bs.BOOK_ID AND b.AUTHOR_ID = a.AUTHOR_ID
    AND (bs.SALES_DATE >= '2022-01-01' AND bs.SALES_DATE < '2022-02-01')
GROUP BY AUTHOR_ID, CATEGORY 
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;