-- 코드를 입력하세요
SELECT gu.USER_ID AS USER_ID, gu.NICKNAME AS NICKNAME, SUM(gb.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER gu, USED_GOODS_BOARD gb
WHERE gu.USER_ID = gb.WRITER_ID
    AND gb.STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING SUM(gb.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;