-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (SELECT MAX(e2.SIZE_OF_COLONY)
     FROM ECOLI_DATA e2
     WHERE YEAR(e1.DIFFERENTIATION_DATE) = YEAR(e2.DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,
     ID
FROM ECOLI_DATA e1
ORDER BY YEAR(e1.DIFFERENTIATION_DATE) ASC, YEAR_DEV ASC;