-- 코드를 입력하세요
SELECT icif.INGREDIENT_TYPE AS INGREDIENT_TYPE, SUM(fh.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF fh, ICECREAM_INFO icif
WHERE fh.FLAVOR = icif.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;